import 'package:timetable_project/models/paccakhan_model.dart';
import 'package:timetable_project/core/utils.dart';

class PaccakhanRepository {
  List<PaccakhanModel> getPaccakhanData() {
    return [
      PaccakhanModel(
        date: '2026-08-21',
        sunrise: '06:21 AM',
        sunset: '06:57 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Navami',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-08-22',
        sunrise: '06:21 AM',
        sunset: '06:57 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dashami',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-08-23',
        sunrise: '06:21 AM',
        sunset: '06:56 PM',
        daylength: '',
        navkarshi: '07:09 AM',
        porsi: '9:30 AM',
        sadhporsi: '11:04 AM',
        purimaddha: '12:39 PM',
        avaddh: '3:47 PM',
        tithi: 'Ekadashi',
        day: 'Sunday',
        goodBadDay: 'Good Day',
      ),

      PaccakhanModel(
        date: '2026-08-24',
        sunrise: '06:21 AM',
        sunset: '06:55 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dwadashi',
        day: '',
        goodBadDay: 'Bad Day',
      ),

      PaccakhanModel(
        date: '2026-08-25',
        sunrise: ' ',
        sunset: ' ',
        daylength: '',
        navkarshi: ' ',
        porsi: ' ',
        sadhporsi: ' ',
        purimaddha: ' ',
        avaddh: ' ',
        tithi: 'Dwadashi',
        day: ' ',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-08-26',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: ' ',
        porsi: ' ',
        sadhporsi: ' ',
        purimaddha: ' ',
        avaddh: ' ',
        tithi: 'Trayodashi',
        day: ' ',
        goodBadDay: 'Bad Day',
      ),
      PaccakhanModel(
        date: '2026-08-27',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Chaturdashi',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-08-28',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Pournima',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-08-29',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Pratipada',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-08-30',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dwitiya',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-08-31',
        sunrise: ' ',
        sunset: ' ',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Tritiya',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-09-01',
        sunrise: ' ',
        sunset: ' ',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Panchami',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-09-02',
        sunrise: ' ',
        sunset: ' ',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Sashti',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-09-03',
        sunrise: ' ',
        sunset: ' ',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Saptami',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-09-04',
        sunrise: ' ',
        sunset: ' ',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Ashtami',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-09-05',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Navami',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-09-06',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dashami',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-09-07',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Ekadashi',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-09-08',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dwadashi',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-09-09',
        sunrise: '06:24 AM',
        sunset: '06:42 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Trayodashi',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-09-10',
        sunrise: '06:24 AM',
        sunset: '06:41 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Chaturdashi',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-09-11',
        sunrise: '06:24 AM',
        sunset: '06:40 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Amavasya',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-09-12',
        sunrise: '06:24 AM',
        sunset: '06:40 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Pratipada',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-09-13',
        sunrise: '06:24 AM',
        sunset: '06:39 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dwitiya',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-09-14',
        sunrise: '06:24 AM',
        sunset: '06:38 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Tritiya',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-09-15',
        sunrise: '06:25 AM',
        sunset: '06:37 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Chaturthi',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-09-16',
        sunrise: '06:25 AM',
        sunset: '06:36 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Panchami',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-09-17',
        sunrise: '06:25 AM',
        sunset: '06:35 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Sashti',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-09-18',
        sunrise: '06:25 AM',
        sunset: '06:34 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Saptami',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-09-19',
        sunrise: '06:25 AM',
        sunset: '06:34 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Ashtami',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-09-20',
        sunrise: '06:25 AM',
        sunset: '06:33 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Navami',
        day: '',
        goodBadDay: 'Good Day',
      ),
    ];
  }
}
