import 'package:timetable_project/models/paccakhan_model.dart';
import 'package:timetable_project/core/utils.dart';

class PaccakhanRepository {
  List<PaccakhanModel> getPaccakhanData() {
    return [
      PaccakhanModel(
        date: '2026-08-21',
        sunrise: '06:21 AM',
        sunset: '06:57 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Navami',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-08-22',
        sunrise: '06:21 AM',
        sunset: '06:57 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dashami',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-08-23',
        sunrise: '06:21 AM',
        sunset: '06:56 PM',
        daylength: '',
        navkarshi: '07:09 AM',
        porsi: '9:30 AM',
        sadhporsi: '11:04 AM',
        purimaddha: '12:39 PM',
        avaddh: '3:47 PM',
        tithi: 'Ekadashi',
        day: 'Sunday',
        goodBadDay: 'Normal Day',
      ),

      PaccakhanModel(
        date: '2026-08-24',
        sunrise: '06:21 AM',
        sunset: '06:55 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dwadashi',
        day: '',
        goodBadDay: 'Normal Day',
      ),

      PaccakhanModel(
        date: '2026-08-25',
        sunrise: ' ',
        sunset: ' ',
        daylength: '',
        navkarshi: ' ',
        porsi: ' ',
        sadhporsi: ' ',
        purimaddha: ' ',
        avaddh: ' ',
        tithi: 'Dwadashi',
        day: ' ',
        goodBadDay: 'Bad Day',
      ),
      PaccakhanModel(
        date: '2026-08-26',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: ' ',
        porsi: ' ',
        sadhporsi: ' ',
        purimaddha: ' ',
        avaddh: ' ',
        tithi: 'Trayodashi',
        day: ' ',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-08-27',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Chaturdashi',
        day: '',
        goodBadDay: 'Bad Day',
      ),
      PaccakhanModel(
        date: '2026-08-28',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Pournima',
        day: '',
        goodBadDay: 'Bad Day',
      ),
      PaccakhanModel(
        date: '2026-08-29',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Pratipada',
        day: '',
        goodBadDay: 'Bad Day',
      ),
      PaccakhanModel(
        date: '2026-08-30',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dwitiya',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-08-31',
        sunrise: ' ',
        sunset: ' ',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Tritiya',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-09-01',
        sunrise: ' ',
        sunset: ' ',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Panchami',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-09-02',
        sunrise: ' ',
        sunset: ' ',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Sashti',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-09-03',
        sunrise: ' ',
        sunset: ' ',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Saptami',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-09-04',
        sunrise: ' ',
        sunset: ' ',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Ashtami',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-09-05',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Navami',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-09-06',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dashami',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-09-07',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Ekadashi',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-09-08',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dwadashi',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-09-09',
        sunrise: '06:24 AM',
        sunset: '06:42 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Trayodashi',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-09-10',
        sunrise: '06:24 AM',
        sunset: '06:41 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Chaturdashi',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-09-11',
        sunrise: '06:24 AM',
        sunset: '06:40 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Amavasya',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-09-12',
        sunrise: '06:24 AM',
        sunset: '06:40 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Pratipada',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-09-13',
        sunrise: '06:24 AM',
        sunset: '06:39 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dwitiya',
        day: '',
        goodBadDay: 'Bad Day',
      ),
      PaccakhanModel(
        date: '2026-09-14',
        sunrise: '06:24 AM',
        sunset: '06:38 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Tritiya',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-09-15',
        sunrise: '06:25 AM',
        sunset: '06:37 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Chaturthi',
        day: '',
        goodBadDay: 'Bad Day',
      ),
      PaccakhanModel(
        date: '2026-09-16',
        sunrise: '06:25 AM',
        sunset: '06:36 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Panchami',
        day: '',
        goodBadDay: 'Bad Day',
      ),
      PaccakhanModel(
        date: '2026-09-17',
        sunrise: '06:25 AM',
        sunset: '06:35 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Sashti',
        day: '',
        goodBadDay: 'Bad Day',
      ),
      PaccakhanModel(
        date: '2026-09-18',
        sunrise: '06:25 AM',
        sunset: '06:34 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Saptami',
        day: '',
        goodBadDay: 'Bad Day',
      ),
      PaccakhanModel(
        date: '2026-09-19',
        sunrise: '06:25 AM',
        sunset: '06:34 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Ashtami',
        day: '',
        goodBadDay: 'Bad Day',
      ),
      PaccakhanModel(
        date: '2026-09-20',
        sunrise: '06:25 AM',
        sunset: '06:33 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Navami',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-09-21',
        sunrise: '06:25 AM',
        sunset: '06:33 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dashami',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-09-22',
        sunrise: '06:25 AM',
        sunset: '06:33 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Ekadashi',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-09-23',
        sunrise: '06:25 AM',
        sunset: '06:33 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dwadashi',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-09-24',
        sunrise: '06:25 AM',
        sunset: '06:33 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Trayodashi',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-09-25',
        sunrise: '06:25 AM',
        sunset: '06:33 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Chaturdashi',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-09-26',
        sunrise: '06:25 AM',
        sunset: '06:33 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Pournima',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-09-27',
        sunrise: '06:25 AM',
        sunset: '06:33 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Pratipada',
        day: '',
        goodBadDay: 'Bad Day',
      ),
      PaccakhanModel(
        date: '2026-09-28',
        sunrise: '06:25 AM',
        sunset: '06:33 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dwitiya',
        day: '',
        goodBadDay: 'Good Day',
      ),
      PaccakhanModel(
        date: '2026-09-29',
        sunrise: '06:25 AM',
        sunset: '06:33 PM',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Tritiya',
        day: '',
        goodBadDay: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-09-30',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Chaturthi',
        day: '',
        goodBadDay: 'Bad Day',
      ),

      PaccakhanModel(
        date: '2026-10-01',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Panchami',
        day: '',
        goodBadDay: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-10-02',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Sashti',
        day: '',
        goodBadDay: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-10-03',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Ashtami',
        day: '',
        goodBadDay: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-10-04',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Navami',
        day: '',
        goodBadDay: 'Normal Day ',
      ),
      PaccakhanModel(
        date: '2026-10-05',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dashami',
        day: '',
        goodBadDay: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-10-06',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Ekadashi',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-10-07',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dwadashi',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-10-08',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Trayodashi',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-10-09',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Chaturdashi',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-10-10',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Amavasya',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-10-11',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Pratipada',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-10-12',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dwitiya',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-10-13',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Tritiya',
        day: '',
        goodBadDay: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-10-14',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Chaturthi',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-10-15',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Panchami',
        day: '',
        goodBadDay: 'Good day',
      ),
      PaccakhanModel(
        date: '2026-10-16',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Sashti',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-10-17',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Saptami',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-10-18',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Saptami',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-10-19',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Ashtami',
        day: '',
        goodBadDay: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-10-20',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Navami',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-10-21',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dashami',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-10-22',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Ekadashi',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-10-23',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dwadashi',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-10-24',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Trayodashi',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-10-25',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Chaturdashi',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-10-26',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Pournima',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-10-27',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dwitiya',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-10-28',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Tritiya',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-10-29',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Chaturthi',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-10-30',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Panchami',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-10-31',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Sashti',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-11-01',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Saptami',
        day: '',
        goodBadDay: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-11-02',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Ashtami',
        day: '',
        goodBadDay: 'Good day',
      ),
      PaccakhanModel(
        date: '2026-11-03',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Navami',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-11-04',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dashami',
        day: '',
        goodBadDay: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-11-05',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Ekadashi',
        day: '',
        goodBadDay: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-11-06',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dwadashi',
        day: '',
        goodBadDay: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-11-07',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Trayodashi',
        day: '',
        goodBadDay: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-11-08',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Chaturdashi',
        day: '',
        goodBadDay: 'Good day',
      ),
      PaccakhanModel(
        date: '2026-11-09',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Amavasya',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-11-10',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Pratipada',
        day: '',
        goodBadDay: 'Good day',
      ),
      PaccakhanModel(
        date: '2026-11-11',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dwitiya',
        day: '',
        goodBadDay: 'Good day',
      ),
      PaccakhanModel(
        date: '2026-11-12',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Tritiya',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-11-13',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Chaturthi',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-11-14',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Panchami',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-11-15',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Sashti',
        day: '',
        goodBadDay: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-11-16',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Saptami',
        day: '',
        goodBadDay: 'Good day',
      ),
      PaccakhanModel(
        date: '2026-11-17',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Ashtami',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-11-18',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Navami',
        day: '',
        goodBadDay: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-11-19',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Navami',
        day: '',
        goodBadDay: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-11-20',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dashami',
        day: '',
        goodBadDay: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-11-21',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dwadashi',
        day: '',
        goodBadDay: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-11-22',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Trayodashi',
        day: '',
        goodBadDay: 'Good day',
      ),
      PaccakhanModel(
        date: '2026-11-23',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Chaturdashi',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-11-24',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Pournima',
        day: '',
        goodBadDay: 'Good day',
      ),
      PaccakhanModel(
        date: '2026-11-25',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Pratipada',
        day: '',
        goodBadDay: 'Good day',
      ),
      PaccakhanModel(
        date: '2026-11-26',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dwitiya',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-11-27',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Tritiya',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-11-28',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Panchami',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-11-29',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Sashti',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-11-30',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Saptami',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-12-01',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Ashtami',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-12-02',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Navami',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-12-03',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dashami',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-12-04',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Ekadashi',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-12-05',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dwadashi',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-12-06',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Trayodashi',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-12-07',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Chaturdashi',
        day: '',
        goodBadDay: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-12-08',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Amavasya',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-12-09',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Pratipada',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-12-10',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Pratipada',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-12-11',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dwitiya',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-12-12',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Tritiya',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-12-13',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Chaturthi',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-12-14',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Panchami',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-12-15',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Sashti',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-12-16',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Saptami',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-12-17',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Ashtami',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-12-18',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Navami',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-12-19',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dashami',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-12-20',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Trayodashi',
        day: '',
        goodBadDay: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-12-21',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Trayodashi',
        day: '',
        goodBadDay: 'Good day',
      ),
      PaccakhanModel(
        date: '2026-12-22',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Trayodashi',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-12-23',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Trayodashi',
        day: '',
        goodBadDay: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-12-24',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Trayodashi',
        day: '',
        goodBadDay: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-12-25',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Dwitiya',
        day: '',
        goodBadDay: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-12-26',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Tritiya',
        day: '',
        goodBadDay: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-12-27',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Chaturthi',
        day: '',
        goodBadDay: 'Good day',
      ),
      PaccakhanModel(
        date: '2026-12-28',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'panchami',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-12-29',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Sashti',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-12-30',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Saptami',
        day: '',
        goodBadDay: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-12-31',
        sunrise: '',
        sunset: '',
        daylength: '',
        navkarshi: '',
        porsi: '',
        sadhporsi: '',
        purimaddha: '',
        avaddh: '',
        tithi: 'Ashtami',
        day: '',
        goodBadDay: 'Normal day',
      ),
    ];
  }
}
