import 'package:timetable_project/models/paccakhan_model.dart';
import 'package:timetable_project/core/utils.dart';

class PaccakhanRepository {
  List<PaccakhanModel> getPaccakhanData() {
    return [
      PaccakhanModel(
        date: '2026-08-20',
        sunrise: '06:21 AM',
        sunset: '06:58 PM',
        navkarshi: '',
        porsi: '09:30 AM',
        sadhporsi: '11:05 PM',
        purimaddha: '12:39 PM',
        avaddh: '03:48 PM',
        tithi: 'Ashtami',
        day: 'Thursday',
        specialday: 'Normal Day',
      ),
      PaccakhanModel(
        date: '2026-08-21',
        sunrise: '06:21 AM',
        sunset: '06:57 PM',
        navkarshi: '7:09 AM',
        porsi: '9:30 AM',
        sadhporsi: '11:05 AM',
        purimaddha: '12:39 PM',
        avaddh: '3:48 PM',
        tithi: 'Navami',
        day: 'Friday',
        specialday: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-08-22',
        sunrise: '06:21 AM',
        sunset: '06:57 PM',
        navkarshi: '7:09 AM',
        porsi: '9:30 AM',
        sadhporsi: '11:04 AM',
        purimaddha: '12:39 PM',
        avaddh: '3:48 PM',
        tithi: 'Dashami',
        day: 'Saturday',
        specialday: 'Bad day',
      ),
      PaccakhanModel(
        date: '2026-08-23',
        sunrise: '06:21 AM',
        sunset: '06:56 PM',
        navkarshi: '07:09 AM',
        porsi: '9:30 AM',
        sadhporsi: '11:04 AM',
        purimaddha: '12:39 PM',
        avaddh: '3:47 PM',
        tithi: 'Ekadashi',
        day: 'Sunday',
        specialday: 'Bad day',
      ),

      PaccakhanModel(
        date: '2026-08-24',
        sunrise: '06:21 AM',
        sunset: '06:55 PM',
        navkarshi: '07:09 AM',
        porsi: '9:30 AM',
        sadhporsi: '11:04 AM',
        purimaddha: '12:38 PM',
        avaddh: '3:47 PM',
        tithi: 'Dwadashi',
        day: 'Monday',
        specialday: 'Bad day',
      ),

      PaccakhanModel(
        date: '2026-08-25',
        sunrise: '06:22 AM',
        sunset: '06:56 PM',
        navkarshi: '07:10 AM',
        porsi: '9:30 AM',
        sadhporsi: '11:04 AM',
        purimaddha: '12:38 PM',
        avaddh: '3:46 PM',
        tithi: 'Trayodashi',
        day: 'Tuesday',
        specialday: 'Normal day',
      ),
      PaccakhanModel(
        date: '2026-08-26',
        sunrise: '06:22 AM',
        sunset: '06:54 PM',
        navkarshi: '07:10 AM',
        porsi: '9:30 AM',
        sadhporsi: '11:04 AM',
        purimaddha: '12:38 PM',
        avaddh: '3:46 PM',
        tithi: 'Chaturdashi',
        day: 'Wednesday',
        specialday: 'Bad day',
      ),
    ];
  }
}
